version: '3'
services:
  # auth-server:
  #   build: ./auth-server
  #   ports:
  #     - "5000:5000"
  resource-server:
    build: ./resource-server
    volumes: 
      - ./resource-server:/usr/src/resource-server
    ports:
      - "5001:5001"
    env_file:
      - ./cognito.env
  client:
    build: ./client
    volumes: 
      - ./client:/usr/src/client
    ports:
      - "3000:3000"
    env_file:
      - ./cognito.env
      - ./client/client.env